name: "validate-favorite-number"
description: Make sure that the favorite number contains only digits and is not 69
author: coveros-phil
inputs:
  event_ctx:
    description: event object from the github context
    required: true

runs:
  using: node16
  main: "dist/index.js"